name: ServiceManagement
version: '${version}'
main: com.servicemanagement.ServiceManagementPlugin
api-version: '1.20'
authors: [ "ServiceManagement" ]
description: Bridges your Minecraft server to a web dashboard via a message broker.
